### PR TITLE
initial SDL_mixer support

### PR DESCRIPTION
**Pull request by OhMeadhbh**
Here's the initial SDL_mixer stuff. The new functions can be found by examining the source, or reading the "Audio Functions" section in the README.md file. It makes node-sdl dependent on libsdl-mixer-1.2 (also documented in the README.)

### CODE REVIEW

**Comment by Freezerburn** [comment]
@OhMeadhbh Can you update SDL_mixer support to work with the recent overhaul, as well as use the SDL2 bindings?

**Comment by OhMeadhbh** [comment]
oh hey. just noticed this. lemme see if i can do that this weekend.

**Comment by Freezerburn** [comment]
Awesome, thanks! Looking forward to it :)

**Comment by Emobe** [comment]
long weekend?

**Comment by darvesh** [comment]
Long one indeed!

**Comment by OhMeadhbh** [comment]
Yes. Absolutely. We're all entitled to my time.

**Pull request closed without merging**
